export const Actions = {
	UPDATE_QUEUE: 'UPDATE_QUEUE',
	UPDATE_COLOR: 'UPDATE_COLOR',
	UPDATE_PAUSEDSTATE:"UPDATE_PAUSEDSTATE",
	UPDATE_SELECTEDTRACK:"UPDATE_SELECTEDTRACK",
	UPDATE_USER:"UPDATE_USER",
	UPDATE_TOKEN:"UPDATE_TOKEN",
	UPDATE_MESSAGES:"UPDATE_MESSAGES",
	UPDATE_ISAUTHENTICATED:"UPDATE_ISAUTHENTICATED"
};
